### ISSUE TITLE
Don't wait for the changes spooler to finish before starting backup doc fetches

### ISSUE THREAD

**Issue by smithsz** [IBM/couchbackup#113]
Currently the backup /_bulk_get POST requests don't start until the changes spooler has finished (see https://github.com/cloudant/couchbackup/blob/master/includes/backup.js#L52).

We should start fetching document batches as soon as the spooler sends the first change.

Related, #100 - _Retry backup spool changes request on failure_.

**Comment by ricellis** [comment]
We tried this as part of the modernization effort, but the downsides actually outweight the benefits (it isn't any faster because the network transfer is the bottleneck anyway). See #698 for details.
